project:
  type: website

website:
  title: "Turul doi, 2024"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

